# SPDX-License-Identifier: GPL-3.0-or-later
"""Build a project's findings JSON from its differential-testing casefiles.

  python scripts/gen_findings.py <project>

Reads targets.toml[project] for the `cases` directory and `matcher` style, then
extracts spec anchors into <project>_findings.json (used for overlap surfacing).
Each standard cites the spec differently, so extraction is per-matcher; the walk
and the TOML casefile shape are shared. A project with no `cases` runs cold.
"""
from __future__ import annotations
import tomllib, glob, re, json, sys, collections
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGETS = ROOT / "targets.toml"
VR_SET = {"AE","AS","AT","CS","DA","DS","DT","FL","FD","IS","LO","LT","OB","OD","OF",
          "OL","OV","OW","PN","SH","SL","SQ","SS","ST","SV","TM","UC","UI","UL","UN",
          "UR","US","UT","UV"}
_SECT = re.compile(r"\d+(?:\.\d+)+")
_INV = re.compile(r"\b[a-z]{2,5}-\d+\b")


def _cases(cases_dir: Path):
    files = glob.glob(str(cases_dir / "**/*.toml"), recursive=True)
    out = []
    for f in files:
        try:
            out.append(tomllib.load(open(f, "rb")))
        except Exception:
            pass
    return out, len(files)


def gen_dicom(cases_dir: Path):
    prefixes, tags, vrs = set(), set(), set()

    def norm(part, a):
        a = re.sub(r"^Annex\s+", "", a.strip().lstrip("§").strip())
        m = re.match(r"^T(\d.*)$", a)
        if m:
            a = "Table " + m.group(1)
        return None if a.lower().startswith("note") else f"{part} {a}"

    def walk_tags(o):
        if isinstance(o, dict):
            [walk_tags(v) for v in o.values()]
        elif isinstance(o, list):
            [walk_tags(v) for v in o]
        elif isinstance(o, str) and re.fullmatch(r"[0-9A-Fa-f]{4},[0-9A-Fa-f]{4}", o):
            tags.add(o.upper())

    cases, n = _cases(cases_dir)
    for t in cases:
        case = t.get("case", {})
        for s in case.get("spec", []) or []:
            m = re.match(r"(PS3\.\d+)\s+(.*)", s.strip())
            if m and m.group(1) in ("PS3.5", "PS3.7"):
                p = norm(m.group(1), m.group(2))
                if p:
                    prefixes.add(p)
        walk_tags(t.get("build", {})); walk_tags(t.get("control", {}))
        blob = (case.get("id", "") + " " + case.get("title", "")).upper()
        vrs.update(w for w in re.findall(r"\b[A-Z]{2}\b", blob) if w in VR_SET)
    return n, {
        "section_prefixes": sorted(prefixes),
        "keywords": sorted(tags) + ["IVLE", "Implicit VR", "Explicit VR", "disjunctive",
                                    "struct", "Group Length", "Defined Term"],
        "vrs": sorted(vrs),
    }


def gen_fhir(cases_dir: Path):
    numbers, concepts, invariants = set(), set(), set()
    cases, n = _cases(cases_dir)
    for t in cases:
        for s in t.get("case", {}).get("spec", []) or []:
            numbers.update(_SECT.findall(s))
            invariants.update(_INV.findall(s))
            c = re.sub(r"^(HL7\s+)?(FHIR|CDA)\s+(R\d\s+)?", "", s.strip(), flags=re.I)
            c = re.sub(r"\bsection\b", " ", c, flags=re.I).replace("§", " ")
            c = _SECT.sub(" ", c)
            c = re.sub(r"\(.*?\)", " ", c)
            c = re.sub(r"\s+", " ", c).strip(" .-")
            if 3 <= len(c) <= 40 and "[" not in c and "regex" not in c.lower() \
                    and "/" not in c and re.search(r"[A-Za-z]", c):
                concepts.add(c)
    return n, {
        "section_numbers": sorted(numbers),
        "concepts": sorted(concepts),
        "invariants": sorted(invariants),
    }


_GEN = {"dicom": gen_dicom, "fhir": gen_fhir}


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: gen_findings.py <project>")
    name = sys.argv[1]
    targets = tomllib.load(TARGETS.open("rb")).get("target", {})
    if name not in targets:
        raise SystemExit(f"unknown project '{name}'. defined: {', '.join(targets)}")
    t = targets[name]
    matcher = t.get("matcher", "none")
    if matcher == "none" or "cases" not in t:
        raise SystemExit(f"project '{name}' has no cases/matcher -- it runs cold (NullMatcher).")
    if matcher not in _GEN:
        raise SystemExit(f"no findings extractor for matcher '{matcher}'")
    cases_dir = Path(t["cases"]).expanduser()
    n, data = _GEN[matcher](cases_dir)
    out = ROOT / f"{name}_findings.json"
    data = {"_comment": f"AUTO-GENERATED by scripts/gen_findings.py {name} "
                        f"({n} casefiles from {cases_dir}). Hand-edit freely.", **data}
    out.write_text(json.dumps(data, indent=2))
    sizes = {k: len(v) for k, v in data.items() if isinstance(v, list)}
    print(f"{name}: {n} casefiles -> {out.name}  {sizes}")


if __name__ == "__main__":
    main()
